# Header
menu:
  #Home: /
  archives: /archives
  book: /read
  #tags: /tag
  #about: /about
rss: /atom.xml

share_menu:
- wechat
- weibo

header_title: 'ç‰§'
disqus_shortname: muyao

# Content
excerpt_link: Read More
fancybox: true
default_thumbnail: http://ww3.sinaimg.cn/large/6b373387gw1f459mggsfsj20hs0ck75m.jpg

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#home info
logo: /images/logo.jpg
sologn: 'However long the night, the dawn will break.'
home_menu:
  Blog: /archives
  Github: https://github.com/muuyao
  Twitter: https://twitter.com/muuyao
  Instagram: https://www.instagram.com/muyao93
  # About: /about

